apiVersion: v1
kind: Service
metadata:
  name: employee-api-pankaj-mysql-service
spec:
  ports:
  -  port: 3306
  selector:
    app: employee-api-pankaj
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-api-pankaj-mysql-deployment
spec:
  selector:
    matchLabels:
      app: employee-api-pankaj
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: employee-api-pankaj
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mssql-config
                key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
